<?xml version="1.0" encoding="utf-8"?>
<!--
  \licens       Software License Agreement (MIT)
  \file         <workspace>/src/pet_mk_iv_description/urdf/zumo_chassi.urdf.xacro
  \authors      stefan.kull@gmail.com (Github ID 'SeniorKullken')
  \repository   https://github.com/kullken/Pet-Mk-IV
  \repository   https://github.com/kullken/pet_mcu_common
  \copyright
  \description  .xacro macro that insert a Pololu Zumo Chassis + 4 wheels + fake rubber belt.
                origin_xyz: In the middle of the PCB, Botton of the battery hatch.

                Robot Chassis (Pololu Zumo in a very simplified design)
                Recomend to set params name='base_link'. 
                This will become the 'groud zero' of the rover/robot.
                Sometimes called 'base_footprint', but I recomend to use name='base_link'
  ____________________________________________________________________________
  \usage
      <robot>
        ....
      <xacro:include filename="$(find pet_mk_iv_description)/urdf/chassis_zumo.urdf.xacro"/>
        ....
      <xacro:chassis_zumo name="base_link" />
        ....
      </robot>
  ____________________________________________________________________________

  Xacro common info:
    The entirety of the code below is reproduced whenever the macro is called.
    We use 'params' to add additional arguments to the macro call, 
    which can be simple parameters, or entire code blocks.
    
  \reference http://wiki.ros.org/xacro
  \reference http://wiki.ros.org/urdf/XML/robot
  \reference http://sdformat.org/

-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="chassis_zumo" params="name" >
    <xacro:property name="chassis_length"  value="0.075"/>   <!-- unit m  -->
    <xacro:property name="chassis_width"   value="0.065"/>   <!-- unit m  -->
    <xacro:property name="chassis_height"  value="0.020"/>   <!-- unit m  -->

    <link name='${name}'>
      <pose>0 0 0 0 0 0</pose>
      
      <visual name='Zumo_Chassis_visual'>
        <origin xyz="0.007 0 ${chassis_height/2}" rpy=" 0 0 0"/>
        <geometry>
          <box size= "${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
        <material name="green"/>  <!-- Color in RViz -->
      </visual>
      <collision name='Zumo_Chassis_visual_collision'>
        <origin xyz="0.007 0 ${chassis_height/2}" rpy=" 0 0 0"/>
        <geometry>
          <box size= "${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
      </collision>
    </link>

  </xacro:macro>
</robot>