<?xml version="1.0" encoding="utf-8"?>
<!--
  \licens       Software License Agreement (MIT)
  \file         <workspace>/src/pet_mk_iv_description/urdf/sensor_mpu6050_imu.urdf.xacro
  \authors      stefan.kull@gmail.com (Github ID 'SeniorKullken')
  \repository   https://github.com/kullken/Pet-Mk-IV
  \repository   https://github.com/kullken/pet_mcu_base
  \copyright    
  \description  .xacro macro that defines a IMU sensor MPU6050 break out board
                origin_xyz: In the middle of the PCB, Botton of the PCB.
  ____________________________________________________________________________
  \usage
      <robot>
        ....
      <xacro:include filename="$(find pet_mk_iv_description)/urdf/sensor_mpu6050_imu.urdf.xacro"/>
        ....
      <xacro:sensor_mpu6050_imu.urdf.xacro name="imu" 
                    origin_xyz="0.000 0.000 0.085"
                    origin_rpy="0 0 0"/>
        ....
      </robot>
  ____________________________________________________________________________

  Xacro common info:
    The entirety of the code below is reproduced whenever the macro is called.
    We use 'params' to add additional arguments to the macro call, 
    which can be simple parameters, or entire code blocks.
    
  \reference http://wiki.ros.org/xacro
  \reference http://wiki.ros.org/urdf/XML/robot
  \reference http://sdformat.org/
  \reference http://gazebosim.org/tutorials?tut=ros_gzplugins#IMUsensor(GazeboRosImuSensor)
  \reference https://github.com/chrisspen/ros_mpu6050_node
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="sensor_mpu6050_imu" params="sensor_name topic origin_xyz origin_rpy">
    <xacro:property name="sensor_gazebo_color" value="Gazebo/Green"/>
    <xacro:property name="sensor_rviz_color"   value="green"/>

    <xacro:property name="pcb_length"    value="0.016"/>  <!-- Box x=16mm  -->
    <xacro:property name="pcb_width"     value="0.020"/>  <!-- Box y=20mm  -->
    <xacro:property name="pcb_thicknes"  value="0.0015"/> <!-- Box z=1.5mm -->

    <link name="${sensor_name}_link">
      
      <visual name="${sensor_name}_visual_pcb">
        <origin xyz="0.00 0.00 ${pcb_thicknes/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${pcb_length} ${pcb_width} ${pcb_thicknes}"/>
        </geometry>
        <material name="${sensor_rviz_color}"/>
      </visual>

      <visual name="${sensor_name}_visual_chip">
        <origin xyz="0.00 0.00 ${pcb_thicknes}" rpy="0 0 0"/>
        <geometry>
          <box size="0.0045 0.0045 0.0015"/>  <!-- Visual chip size on top of pcb-->
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <mass value="1e-5" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
      </inertial>
    </link>

    <joint name="${sensor_name}_joint" type="fixed">
      <axis xyz="0 1 0" />
      <origin xyz="${origin_xyz}" rpy="${origin_rpy}" />
      <parent link="base_link"/>
      <child link="${sensor_name}_link"/>
    </joint>

    <gazebo reference="${sensor_name}_link">
      <material>${sensor_gazebo_color}</material>
    </gazebo>
    
    <!--
       \todo Gazebo-simulator plugin-description...=> Move to a separate Gazebo package?
    -->
    <gazebo reference="${sensor_name}_link">
      <gravity>true</gravity>
      <sensor name="imu_sensor" type="imu">
        <always_on>true</always_on>
        <update_rate>100</update_rate>
        <visualize>true</visualize>
        <topic>__default_topic__</topic>
        <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
          <topicName>${topic}</topicName>
          <bodyName>${sensor_name}_link</bodyName>
          <updateRateHZ>10.0</updateRateHZ>
          <gaussianNoise>0.0</gaussianNoise>
          <xyzOffset>0 0 0</xyzOffset>
          <rpyOffset>0 0 0</rpyOffset>
          <frameName>${sensor_name}_link</frameName>
          <initialOrientationAsReference>false</initialOrientationAsReference>
        </plugin>
        <pose>0 0 0 0 0 0</pose>
      </sensor>
    </gazebo>

  </xacro:macro>
</robot>