<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!--
    *****************************************************************
    <workspace>/src/pet_mk_iv_description/urdf/wheel.urdf.xacro
    author: "SeniorKullken" <stefan.kull@gmail.com>
    licens: MIT
       
    Usage example:
      <robot>
        ....
        <xacro:include filename="$(find pet_mk_iv_description)/urdf/wheel.urdf.xacro"/>
        <xacro:wheel  wheel_prefix="front_left"  
                      origin_xyz="${wheel_axis_distance/2} ${wheel_axis_width/2} ${chassis_height/2}"
                      origin_rpy="0 0 0"/>
        <xacro:wheel  wheel_prefix="front_right" 
                      origin_xyz="${wheel_axis_distance/2} -${wheel_axis_width/2} ${chassis_height/2}"
                      origin_rpy="0 0 0"/>
      </robot>
      
    Xacro common info:
      The entirety of the code below is reproduced whenever the macro is called.
      We use 'params' to add additional arguments to the macro call, 
      which can be simple parameters, or entire code blocks.
      See http://wiki.ros.org/xacro for more details.
    *****************************************************************
  -->
  <xacro:macro name="wheel" params="wheel_prefix origin_xyz origin_rpy">


    <link name="${wheel_prefix}_wheel">
      <visual> <!-- name="${wheel_prefix}_wheel_visual"> -->
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <geometry>
          <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>    <!-- Color in RViz -->
      </visual>
      <visual> <!-- name="${wheel_prefix}_wheel_visual_2"> -->
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <geometry>
          <cylinder radius="${wheel_diameter/4}" length="${wheel_width*1.10}"/>
        </geometry>
        <material name="orange"/>    <!-- Color in RViz -->
      </visual>

      <collision name="${wheel_prefix}_wheel_collision">
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <geometry>
          <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
        </geometry>
      </collision>
      
      <inertial>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <mass value="5"/>
        <inertia
          ixx=".1" ixy="0.0" ixz="0.0"
          iyy=".1" iyz="0.0"
          izz=".1"/>
      </inertial>
    </link>

    <joint type="continuous" name="${wheel_prefix}_wheel_joint">
      <origin xyz="${origin_xyz}" rpy="${origin_rpy}"/> <!-- Wheel position rel. <parent link> -->
      <child link="${wheel_prefix}_wheel"/>
      <parent link="base_link"/>
      <axis xyz="0 1 0" rpy="0 0 0"/>  <!-- Wheel rotate around Y-axis -->
      <limit effort="10000" velocity="1000"/>
      <joint_properties damping="1.0" friction="1.0"/>
    </joint>

    <gazebo reference="${wheel_prefix}_wheel">
      <material>Gazebo/Grey</material>
    </gazebo>
  </xacro:macro> 
</robot>